/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const projectId = supabaseUrl
  ? supabaseUrl.replace("https://", "").replace(".supabase.co", "")
  : "spahmuawycgohcznathc";

export const publicAnonKey = supabaseAnonKey || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwYWhtdWF3eWNnb2hjem5hdGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNDEwMDksImV4cCI6MjA4ODcxNzAwOX0.W66FwTKxo3s0_v0kTFlEQkqYC3OOPRKpi8iNyEcmIqw";
