/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const projectId = supabaseUrl
  ? supabaseUrl.replace("https://", "").replace(".supabase.co", "")
  : "";

export const publicAnonKey = supabaseAnonKey || "";
